/**
 * Starter reference accounts per persona (well-known creators in each niche).
 * These are suggestions to prune, not endorsements; handles are the public
 * handles as commonly used on each platform and may need correcting.
 */
export const DEFAULT_COMPETITORS = {
  ginger: [
    { platform: "youtube", handle: "tuckerbudzyn" },
    { platform: "youtube", handle: "itsdougthepug" },
    { platform: "youtube", handle: "MayaPolarBear" },
    { platform: "instagram", handle: "itsdougthepug" },
    { platform: "instagram", handle: "jiffpom" },
    { platform: "instagram", handle: "tuckerbudzyn" },
    { platform: "instagram", handle: "whataboutbunny" },
    { platform: "instagram", handle: "herkythecavalier" },
    { platform: "tiktok", handle: "tuckerbudzyn" },
    { platform: "tiktok", handle: "itsdougthepug" },
    { platform: "x", handle: "itsdougthepug" },
  ],
  frank: [
    { platform: "youtube", handle: "ColeandMarmalade" },
    { platform: "youtube", handle: "nalacat" },
    { platform: "instagram", handle: "nala_cat" },
    { platform: "instagram", handle: "coleandmarmalade" },
    { platform: "instagram", handle: "smoothiethecat" },
    { platform: "instagram", handle: "hosico_cat" },
    { platform: "instagram", handle: "thatlittlepuff" },
    { platform: "instagram", handle: "venustwofacecat" },
    { platform: "tiktok", handle: "thatlittlepuff" },
    { platform: "tiktok", handle: "nalacat" },
    { platform: "x", handle: "nala_cat" },
  ],
  molly: [
    { platform: "youtube", handle: "emmachamberlain" },
    { platform: "youtube", handle: "mikaylanogueira" },
    { platform: "instagram", handle: "alixearle" },
    { platform: "instagram", handle: "mikaylanogueira" },
    { platform: "instagram", handle: "meredithduxbury" },
    { platform: "instagram", handle: "katiefanggg" },
    { platform: "instagram", handle: "naraazizasmith" },
    { platform: "tiktok", handle: "keith_lee125" },
    { platform: "tiktok", handle: "alixearle" },
    { platform: "tiktok", handle: "mikaylanogueira" },
    { platform: "x", handle: "alixearle" },
  ],
  jeff: [
    { platform: "youtube", handle: "JeffNippard" },
    { platform: "youtube", handle: "athleanx" },
    { platform: "youtube", handle: "JeremyEthier" },
    { platform: "youtube", handle: "WillTennyson" },
    { platform: "youtube", handle: "sam_sulek" },
    { platform: "instagram", handle: "chrisheria" },
    { platform: "instagram", handle: "jeffnippard" },
    { platform: "instagram", handle: "noeldeyzel_bodybuilder" },
    { platform: "instagram", handle: "whitneyysimmons" },
    { platform: "tiktok", handle: "chrisheria" },
    { platform: "x", handle: "jeffnippard" },
  ],
  katie: [
    { platform: "youtube", handle: "markiplier" },
    { platform: "youtube", handle: "jacksepticeye" },
    { platform: "youtube", handle: "Valkyrae" },
    { platform: "youtube", handle: "ludwig" },
    { platform: "youtube", handle: "SkillUp" },
    { platform: "youtube", handle: "GirlfriendReviews" },
    { platform: "instagram", handle: "valkyrae" },
    { platform: "instagram", handle: "pokimanelol" },
    { platform: "tiktok", handle: "pokimane" },
    { platform: "x", handle: "Valkyrae" },
    { platform: "x", handle: "pokimanelol" },
  ],
  jenn: [
    { platform: "youtube", handle: "mreflow" },
    { platform: "youtube", handle: "aiexplained-official" },
    { platform: "youtube", handle: "TwoMinutePapers" },
    { platform: "youtube", handle: "WesRoth" },
    { platform: "youtube", handle: "MattVidPro" },
    { platform: "instagram", handle: "lilmiquela" },
    { platform: "instagram", handle: "fit_aitana" },
    { platform: "instagram", handle: "rileybrown.ai" },
    { platform: "tiktok", handle: "rileybrown.ai" },
    { platform: "x", handle: "mreflow" },
    { platform: "x", handle: "rowancheung" },
    { platform: "x", handle: "alliekmiller" },
  ],
  nicole: [
    { platform: "youtube", handle: "drewbinsky" },
    { platform: "youtube", handle: "LostLeBlanc" },
    { platform: "youtube", handle: "KaraandNate" },
    { platform: "youtube", handle: "EvazuBeck" },
    { platform: "youtube", handle: "yestheory" },
    { platform: "instagram", handle: "drewbinsky" },
    { platform: "instagram", handle: "gypsea_lust" },
    { platform: "instagram", handle: "jackmorris" },
    { platform: "instagram", handle: "muradosmann" },
    { platform: "tiktok", handle: "drewbinsky" },
    { platform: "x", handle: "nomadicmatt" },
  ],
};

/** Short category shown under the actor's name. */
export const DEFAULT_CATEGORIES = {
  ginger: "Pets · Dog",
  frank: "Pets · Cat",
  molly: "Food · Workout · Makeup",
  jeff: "Fitness",
  katie: "Video Games",
  jenn: "AI",
  nicole: "Travel",
};
